### ISSUE TITLE
Elm Copenhagen October 2015 Meet Up

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#1]
Elm Copenhagen October 2015 Meet Up

**Date and time**: October 28.
**Location**:

> Zendesk
> Snarregade 12, 1st floor
> 1208 København K
> [map](https://www.google.dk/maps/place/Snaregade+12,+1205+K%C3%B8benhavn+K/@55.6769883,12.5763207,17z/data=!3m1!4b1!4m2!3m1!1s0x4652531141140fcd:0x5af1c8ff9aea8061)

Proposed schedule:
18.00 - 19.00 : Newcomers hands-on intro to Elm (@madsflensted)
19.00 - 20.45 : We team up and work on a given problem and end by sharing and discussing our solutions (group activity)
20.45 - 21.00 : Lightening demos

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [x] a problem for the collaborative session

**Comment by madsflensted** [comment]
Based on our experience at the last Elixir meetup, cphex/cphex/issues/28, I suggest that we start off with the [Yatzy](https://en.wikipedia.org/wiki/Yatzy) theme, there should be plenty of areas that would make some good material for Elm challenges.

**Comment by madsflensted** [comment]
I am suggesting October 27 or 28.

**Comment by madsflensted** [comment]
@gausby, @lehoff, @jacobat,  @malthejorgensen, @emilbayes, @valberg, @skovsgaard  The Elm Copenhagen Meetup group is now a reality. Spread the word, and join in the planning.

The Meetup.com group is here: http://www.meetup.com/Elm-Copenhagen

**Comment by jacobat** [comment]
Oct. 27 does not work for me. If we can do october 28 Zendesk will be happy to host.

**Comment by madsflensted** [comment]
@jacobat that sounds like a great argument for choosing the 28th !

Thank you for offering a location. I will update the issue.

**Comment by madsflensted** [comment]
@jacobat what is address for your offices?

**Comment by jacobat** [comment]
We're at Snaregade 12, 1st floor.

https://www.google.dk/maps/place/Snaregade+12,+1205+K%C3%B8benhavn+K/@55.6769883,12.5763207,17z/data=!3m1!4b1!4m2!3m1!1s0x4652531141140fcd:0x5af1c8ff9aea8061?hl=da

**Comment by jacobat** [comment]
I ported the Yatzy exercises from Cphex to Elm in case we want to use those: https://github.com/jacobat/elm-yatzy

**Comment by lehoff** [comment]
@jacobat: that is a very good starting point! Awesome!!

I wasn't at the Elixir event (sadly), but presenting this we need to
emphasise that the tests do not cover all aspects of the rules and part of
the coding is to ensure that the tests cover more devious cases like, say,
you have three of a kind, but want to use the score as one of a kind. Or
use a full house as two pairs.

And the nifty pattern matching tricks that I used in my Elixir solution
will not work for Elm... the type system stops it.

On 27 September 2015 at 19:34, Jacob Atzen notifications@github.com wrote:

> I ported the Yatzy exercises from Cphex to Elm in case we want to use
> those: https://github.com/jacobat/elm-yatzy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elmcph/elmcph/issues/1#issuecomment-143580021.

## 

http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by cyberglot** [comment]
:+1:

**Comment by madsflensted** [comment]
@jacobat good idea porting the test code.

**Comment by jacobat** [comment]
I don't know how idiomatic the code is. Feel free to improve upon it if you see something that could be better.

**Comment by jacobat** [comment]
@madsflensted Can I get you to limit the number of attendees to 30 in Meetup? We can't accomodate more than that unfortunately.

**Comment by madsflensted** [comment]
Was thinking the same. As we need room to work,  should the number be
lower?

**Comment by madsflensted** [comment]
I have set limit to 25 for now

**Comment by jacobat** [comment]
There is sufficient space to hold 30 people.

**Comment by madsflensted** [comment]
Ok - have raised the limit to 30

**Comment by madsflensted** [comment]
29 - reserved a non-meetup spot for @keleshev

**Comment by keleshev** [comment]
Thanks @madsflensted. I would also love if you could find a 5-minute time slot for a lightning talk where I could present my half-baked Elm game: https://github.com/keleshev/TankYou.

**Comment by madsflensted** [comment]
Great idea. Will add some time at the end for demos.

My plan is to send out a quick/short poll to figure out where people attending are with Elm.

**Comment by madsflensted** [comment]
@jacobat I am working on a mini-survey I want to send out before our first meetup, could I get you to [test it](https://docs.google.com/forms/d/1_QldT91-MtDp0P1C-ymlwGwrlvMFMcVcmHw2EgxZ8jM/viewform) out? And give some feedback (on the content) :-)

**Comment by malthejorgensen** [comment]
@madsflensted I tried out the survey just now – looks fine! :)

**Comment by jacobat** [comment]
@madsflensted It would make it easier for me to provide feedback if you could you say a bit about what the purpose is and what you're hoping to get out of it?

**Comment by madsflensted** [comment]
@jacobat I guess was just curious as to where people are with Elm. But for now just check that 
- survey works for somebody other than me
- no obvious mistakes
- is there something else that would be worth asking

@malthejorgensen thanks

**Comment by jacobat** [comment]
One thing I notice is that it says "Andet" and not "Other" and the Google disclaimer and stuff is in Danish as well. Probably because I'm somehow configured as Danish?

Another nit-picky thing is the wording "What OS do (plan to) use for you elm adventures?" which I believe should be "What OS do you (plan to) use for your elm adventures?".

Apart from that it looks just fine. I think it's a nice idea to get a grasp of the level people are at.

**Comment by madsflensted** [comment]
@jacobat thank you! Wording updated for OS question.
The danish/english seems to be one those "smart things" where browser detects your language :-(

**Comment by madsflensted** [comment]
(Copy of messages sent to meetup members)
Hi Elm Copenhagen!

October is here and our first meetup is only 2 weeks away. I am really looking forward to meeting people and digging into elm together.

To give us all an initial idea of our collective elm background I have put together a very short survey, and it would be great if you could take a minute to submit your feedback. You can find the form here https://docs.google.com/forms/d/1_QldT91-MtDp0P1C-ymlwGwrlvMFMcVcmHw2EgxZ8jM/viewform

The idea is to use the first three meet-ups to focus on different basic areas of elm, and then take it from there:
1. Elm syntax, Data types and how to get something on the screen
2. Elm the reactive parts
3. The elm architecture pattern

We'll see how this plays out.

If you have ideas for challenges that we can use for any of these areas, just post them on our github meetup issue: https://github.com/elmcph/elmcph/issues/1

On request I have added some room at the end of the program for lightening demos, so if you already have some working elm code that you would like to show, and can do it in 3-4 minutes, then bring it to the meetup.

Br
Mads

**Comment by madsflensted** [comment]
@keleshev above is for you

**Comment by jacobat** [comment]
I've had fun playing with https://github.com/pdamoc/elmChallenges - perhaps an option for more advanced elm learning.

**Comment by madsflensted** [comment]
Great, let's see what we can gather. Maybe there are also some general coding challenges we can use. Will look around.

I worked through the [yatzy scorer challenge](https://github.com/jacobat/elm-yatzy) that @jacobat ported to Elm. And it is actually still interesting the 2nd time around, and a good fit for core Elm code. I think it would make a good candidate for 1st meetup.

**Comment by madsflensted** [comment]
I can see  @justalisteningman is working on creating an [Elm language track](https://github.com/justalisteningman/xelm)  for http://exercism.io

That will be a great learning resource as well. Maybe we can contribute with some testing?

**Comment by bewatts** [comment]
Hello, Copenhagen Elmers / Elmites / Elm enthusiasts!

Contributions / PR's are more than welcome!  

Here are ways people can help:
-- Look to the [haskell language track](https://github.com/exercism/xhaskell), see what tests haven't been implemented, and are appropriate for elm. 
-- Getting it to run on Travis would be a godsend. 
--  Updating the docs to be more helpful!
-- Make the example code better for any of the tests.
-- Consider the elm-lang docs - what elm-specific information hasn't been included in our tests so far?        What conceptual holes are missing?

**Comment by madsflensted** [comment]
@justalisteningman I think it is great that you are working on this! I will make sure to promote the project at our next meetup, and see if we can get somebody to help out.

**Comment by madsflensted** [comment]
Email gone out to meetup rsvp's:

Hi Elm'ers

our first Meetup is now only a few days away, there is a full house and we hope that everybody can still make it.

Our generous host is sponsoring Pizza and beverages, so we will be all set for an evening of elm!

Also it is a good time to check that your elm installation is up to date. We will be working with the Elm Platfom 0.15.1. There are ﻿installers for [Mac and Windows](http://elm-lang.org/install)﻿ and on Linux you can use the [npm binary installer](https://www.npmjs.com/package/elm) or build from source (but this option can get you into some Haskell/cabal challenges).

In addition we will use an elm test module in the second half that uses [nodejs](https://nodejs.org/) to run tests - so having nodejs installed is also a good idea.

If for some reason you cannot make it anyway, please update your RSVP, so that somebody else can join instead.

See you all on Wednesday.

Mads and Jacob

**Comment by madsflensted** [comment]
http://madsflensted.github.io/connect-four/

**Comment by skovsgaard** [comment]
Sorry to be this late about it, but I'm not gonna make it tonight.

**Comment by madsflensted** [comment]
@skovsgaard too bad - missing out on elm AND pizza - tough one!

**Comment by d99m** [comment]
I wish I followed the #ElmLang twitter tag earlier to find out about this meet up! Hopefully next time!

**Comment by naxoc** [comment]
I work at Dagbladet Information located in Kongens Nytorv. We have plenty of space for meetups, so if we need a location in the future we can do a meetup there.

**Comment by gausby** [comment]
Hey

Nice meet up. I have one critique though; In the opening example I would have preferred something visual. Something I could interact with; so if it could start out with an example that went from the view to the model, instead of the model to the view, it would have been preferable.

Otherwise, great meet up. The yatzy task was fun. Great food. Great people. See you at the next meet up.

(…and we do have an Elixir meet up November 17)

**Comment by madsflensted** [comment]
@gausby I think that is a great idea, will see how that can influence the next intro session.

If anybody else has feedback - don't hold back.

(... and the the link to the [Elixir Meetup](https://github.com/cphex/cphex/issues/32) )

**Comment by madsflensted** [comment]
Thank you all for a great first meeting. A special thanks to @jacobat and Zendesk - couldn't have dreamed of a better venue for this! 

@naxoc that would be great! If we go for "last Wednesday of the month" - then maybe it could be at Information for the January 27th one?

The November Meetup is open for input here [#4].

**Comment by madsflensted** [comment]
I have pushed my attempt at a solution to the [Yatzy Scorer challenge](https://github.com/jacobat/elm-yatzy).

If you finished some of work then consider forking and pushing the repository with your solution - so others can learn from your way of approaching the problem.

You can see all forks [here](https://github.com/jacobat/elm-yatzy/network).

**Comment by lehoff** [comment]
I have written a bit about my Yatzy score solution @ http://beamster.org/yatzy-pattern-elm.html

**Comment by madsflensted** [comment]
@lehoff thanks for sharing your you sugar-shocked-brain-dump about that Yatzy problem - very nice solution! Pattern matching really makes things easy to understand (once you get to the point where you can actually use it :-)

**Comment by madsflensted** [comment]
@knikel  - sorry you missed it. I hope you make it to round 2 [#4]
