### ISSUE TITLE
Elm Copenhagen September 2016 Meetup

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#11]
Elm Copenhagen September 2016 Meetup

**Date**: September 29
**Time**: 18.00 - 21.00
**Location**: 

> [Bownty](https://bownty.dk/about)
> Vimmelskaftet 43 2. sal
> 1161 København K
> 
> [Map](https://www.google.dk/maps/place/Vimmelskaftet+43,+1161+K%C3%B8benhavn+K/@55.678579,12.5729543,17z/data=!3m1!4b1!4m5!3m4!1s0x4652531103d58fcb:0x21e0411330605e59!8m2!3d55.678576!4d12.575143?hl=en)

@halfzebra willl give an introduction to how you can quick start an elm project.

Afterwards everybody can work on the area that they find most interesting and team up with others to get help or just share problems and progress.

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [ ] whether food/drink/snacks are available or if we pool our cash and send out for take away

**Comment by madsflensted** [comment]
@lorenzo @naruvimama let's plan from here

**Comment by lorenzo** [comment]
We can host the meetup at Bownty. End of September would be perfect for us.

**Comment by madsflensted** [comment]
That sounds great. Any preference for 26 - 29?

**Comment by lorenzo** [comment]
The 29th

**Comment by madsflensted** [comment]
great - updated issue.
Do you have an address and map link?

**Comment by madsflensted** [comment]
@lorenzo and @halfzebra any of you up for giving an introduction to Elm for begginers? like 1/2 hour?

**Comment by lorenzo** [comment]
@madsflensted Vimmelskaftet 43 2. 

https://www.google.dk/maps/place/Vimmelskaftet+43,+1161+K%C3%B8benhavn+K/@55.678579,12.5729543,17z/data=!3m1!4b1!4m5!3m4!1s0x4652531103d58fcb:0x21e0411330605e59!8m2!3d55.678576!4d12.575143?hl=en

Small nitpick, it is "Bownty" and not "Bounty". Bounty would be tastier, though 🍫

**Comment by madsflensted** [comment]
@lorenzo ha yes maybe it would.

**Comment by madsflensted** [comment]
Ok announced on Meetup

**Comment by ghost** [comment]
I would love to come but it collides with the Faculty of Computer Science, Copenhagen University (DIKU) alumni day :(
- [DIKU Alumnedag 2016](http://diku.dk/begivenhedsmappe/begivenheder-2016/diku-alumnedag/)

I'll guess I see you at the October Meetup :+1:

**Comment by madsflensted** [comment]
@gentauro I hope you enjoy the alumni day.

**Comment by halfzebra** [comment]
@madsflensted I can give a little intro for newcomers(around 15-20 minutes) about quick-starting with Elm, if the time is still available.

Please let me know, thank you!

**Comment by lorenzo** [comment]
@halfzebra I think that would be great, and as far as I know the speaking spot is still available :)

**Comment by ghost** [comment]
A few Elm people are coming to CPH due to GOTO: @coreyhaines, @luke (from https://elmlang.slack.com/) and @niels and myself are going for a beer on 2016-10-02 @ Nyhavn.

@madsflensted, could you create an ad-hoc event for this? And please join to meet people IRL :) (also on Slack)

**Comment by madsflensted** [comment]
@halfzebra that would be awesome. I  have updated description here and will send out an update on Meetup + twitter.

**Comment by madsflensted** [comment]
@gentauro absolutely, great idea, will get that out over the weekend.

**Comment by ghost** [comment]
> @gentauro absolutely, great idea, will get that out over the weekend.

@coreyhaines says he will confirm as it's not 100%, so we will hold or horses until he finally confirms :)

**Comment by madsflensted** [comment]
@lorenzo thank you for organizing this. Did anybody show up that could be a potential host for the next one?

**Comment by coreyhaines** [comment]
Hey, all. I chatted with Luke, and I think we'll be up for hanging out.

**Comment by madsflensted** [comment]
@coreyhaines excellent, you can organize on this issue #12
