### ISSUE TITLE
Elm Copenhagen pre-GOTO hang out

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#12]
Elm Copenhagen pre-GOTO Beers

**Date**: October 2 2016
**Time**: 19.00 - ??
**Location**: 

> Nyhavn 17
> 1051 København K
> 
> http://www.nyhavn17.dk/

**Comment by madsflensted** [comment]
@gentauro @coreyhaines
You can organize the event here and I will put on Meetup/Twitter when you have the details down.

**Comment by ghost** [comment]
@madsflensted cool.

I would say that I can go for 1-2 beers (at most) :)

We can meet @ Nyhavn tomorrow (2016-10-02). What time would suit you best @coreyhaines?

**Comment by nsb** [comment]
I said I would be there, but I'm down with the flu.

Den lør. 1. okt. 2016 10.59 skrev Ramón Soto Mathiesen <
notifications@github.com>:

**Comment by coreyhaines** [comment]
How about 7pm? We land at 4pm. I'll see Luke today and let him know. Is the
location close to the goto hotel?

**Comment by ghost** [comment]
@nsb sad to hear :(

@coreyhaines It's just 20 minutes (with Metro from the hotel):

https://goo.gl/B9J1DW

**Comment by madsflensted** [comment]
@gentauro can you add a precise location to meet? E.g. Bar. And then we can
announce it

**Comment by coreyhaines** [comment]
Is there any chance of getting it closer to the goto hotel? Would help us
out.

**Comment by ghost** [comment]
@madsflensted http://www.nyhavn17.dk/? (Nyhavn 17, 1051 København K, Danmark)

@coreyhaines you live like out in a small island, where there is nothing besides the congress centre (you will see that as soon as you arrive). It reminds a bit of NDC Londons location compared to London ;) (if you guys have been to that one).

**Comment by coreyhaines** [comment]
OK.  No worries.

**Comment by madsflensted** [comment]
I have announced on Meetup and Twitter. @gentauro I have set you as organizer.

**Comment by madsflensted** [comment]
so you will get responses

**Comment by ghost** [comment]
@madsflensted roger :)

@coreyhaines I've just realized that you guys are speakers. I thought you were participants, doh

**Comment by coreyhaines** [comment]
:) We're Elm lovers. :) @lukewestby is even talking about Elm.

**Comment by ghost** [comment]
Yeah, I'm just realizing that is "that" luke ;) (I even spoke about how I wanted to see his talk at GOTO) :D

**Comment by coreyhaines** [comment]
:) He's pretty great.

**Comment by ghost** [comment]
Yeah, so his talk from the elm-conf. Really looking forward to talk to you guys tomorrow :+1:

**Comment by lukewestby** [comment]
Y'all are too much 😊 

> "that" luke ;)

new twitter name

@coreyhaines and I are waiting for our flight across the atlantic to board. can't wait to meet you all!

**Comment by ghost** [comment]
:D 

(btw, it's looks like nobody is joining the pre-event meetup ... :-1:)

**Comment by gausby** [comment]
I am out of town (at my parents place) but I hope to make it back to Copenhagen in time so I can join this event ^_^

**Comment by coreyhaines** [comment]
Hey, All,

I need to bail on meeting up. After getting to the hotel after something like 19 or 20 hours travel, I just don't have any more in me. Need to settle in and sleep. I don't know about @luke, but I'm pinging him about getting there. I'm sorry about cancelling, but having trouble just keeping my head clear.

**Comment by ghost** [comment]
@coreyhaines it's all good man. Jet-lag is not pleasant, we all know that.

Get some rest and be ready for the GOTO conference, I guess I'll catch you on Slack (if I'm able to connect ... for the time it just freezes cos of the many non-viewed unread messages)

p.d.: Lets wait for @lukewestby, if he is tired as well, we might just call it of :)

**Comment by coreyhaines** [comment]
Thanks for understanding.

**Comment by lukewestby** [comment]
I'll be there!

**Comment by ghost** [comment]
![cool_hand_luke](https://cloud.githubusercontent.com/assets/78475/19021868/0e80715a-88cb-11e6-9483-429e0af8b99b.jpg)

**Comment by ghost** [comment]
sry, "that" Luke :)

**Comment by lukewestby** [comment]
So since I'm going over by myself and I shaved my beard, this is what I look like right now so it's easier to find me

![photo on 10-2-16 at 6 17 pm 2](https://cloud.githubusercontent.com/assets/1508245/19021919/89a563c6-88cc-11e6-9b91-818c35a65cba.jpg)

**Comment by ghost** [comment]
It's raining like there is no tomorrow. Never mind, I biked so :)

**Comment by madsflensted** [comment]
so you will get responses
