### ISSUE TITLE
Elm Copenhagen October 2016 Meetup

### ISSUE THREAD

**Issue by lorenzo** [elmcph/elmcph#13]
Elm Copenhagen October 2016 Meetup

**Date**: Wednesday, October 26
**Time**: 18.00 - 21.00
**Location**: Bownty. Vimmelskaffet 43, 2.

> [Map](https://www.google.com/maps?f=q&hl=en&q=Vimmelskaftet+43+2.sal,+Copenhagen,+dk)

If somebody wants to present something Elm'ish, maybe something that they have been working on or have been looking at - we will kick off with that, taking at most 15 minutes. Afterwards everybody can work on the area that they find most interesting and team up with others to get help or just share problems and progress.

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [x] food/drink/snacks available: No

**Comment by lorenzo** [comment]
I'm opening this ticket to start planing again this month's meet up. I'd be glad to host it again at Bownty if needed :)

**Comment by madsflensted** [comment]
@lorenzo I have made you co-organizer on Meetup, so you can also create the event there if you find a suitable date.

The easiest is to simply set the date, announce it on Meetup and then we can tweet about it as well

**Comment by lorenzo** [comment]
Great, thanks @madsflensted

**Comment by lorenzo** [comment]
would Thursday 27 be ok?

**Comment by ghost** [comment]
Lets move the discussion to here. For me on that week I can all days except those 2 (Tuesday I'm hosting MF#K and on Thursday we have "generalforsamling" where I live) :+1:

**Comment by lorenzo** [comment]
@gentauro Wednesday?

**Comment by ghost** [comment]
Fine with me :)

**Comment by lorenzo** [comment]
@madsflensted Can you please tweet it?

**Comment by madsflensted** [comment]
@lorenzo absolutely

**Comment by ghost** [comment]
@lorenzo just to be sure, I have big HDMI (Type A) on my laptop and I don't have any adapters (I switched from Mac to Razer a few months ago). Do I need to purchase some kind of multi-adapater or do you have any at Bownty?

**Comment by lorenzo** [comment]
I will check and let you know

**Comment by ghost** [comment]
![elm_talk](https://cloud.githubusercontent.com/assets/78475/19678150/d8520056-9a9c-11e6-9bec-ca24ae8a2647.png)

**Comment by ghost** [comment]
> I will check and let you know 

@lorenzo any news on this one? Should I just go buy a multi- adaptor, just in case? I might be able to buy one in Humac on the way to Bownty.

**Comment by lorenzo** [comment]
@gentauro i think that might be the best, I could only find here the hdmi connectors MacBook pros use

**Comment by ghost** [comment]
Roger that
