### ISSUE TITLE
Elm Copenhagen November 2016 Meetup

### ISSUE THREAD

**Issue by halfzebra** [elmcph/elmcph#14]
Elm Copenhagen November 2016 Meetup

**Date**: November 21th 2016
**Time**: 17.30 - 20.00
**Location**:
> Flæsketorvet 28 , Copenhagen
> [Map](https://www.google.dk/maps/place/Fl%C3%A6sketorvet+28,+1711+K%C3%B8benhavn+V/@55.6676429,12.5558217,17z/data=!3m1!4b1!4m5!3m4!1s0x46525373ed9ee5f7:0xfc278e459cd1ede2!8m2!3d55.6676429!4d12.5580104)

Speakers:
@lorenzo will be speaking "Functional patterns for creating elegant applications in Elm"
@terezka will have a talk about her elm-plot library
@halfzebra if I will have time, I'll give a short intro to elm DevOps tooling

* * *
We need to find and decide upon:

  * [x] a venue
  * [x] a date
  * [x] a time
  * [x] food/drink/snacks available: FooCafe

**Comment by madsflensted** [comment]
@halfzebra I have made you co-organizer on Meetup group. Just set at date and Venue here on GH. Then create an event on Meetup. If you need inspiration/help just let me know.

**Comment by lorenzo** [comment]
My preferred dates are 21, 23 and 24. I can present par of the talk I'll be doing in øredev

**Comment by halfzebra** [comment]
@madsflensted awesome! Thank you!
@lorenzo sounds very good, 24th would be the best for me, I'm attending the language school on 21/23 😧

**Comment by eikooc** [comment]
24th also works for me :smile:

**Comment by halfzebra** [comment]
@eikooc unfortunately we have to move the date to 21th

@lorenzo @madsflensted I will announce the meetup at meetup.com tomorrow, still have to wait for the final confirmation from FooCafe.

**Comment by lorenzo** [comment]
@halfzebra did you get confirmation?

**Comment by halfzebra** [comment]
@lorenzo I'm afraid we have to re-schedule the meetup, still haven't got the confirmation from FooCafe.

Let's schedule a new one for December. I have a couple more venues on my mind, so I'll try to get more options this time. Please hit me with a message if you'll have any suggestions!

**Comment by lorenzo** [comment]
Ok, I think that's wise... there is no need to rush it
