### ISSUE TITLE
Elm Copenhagen December 2016 Meetup

### ISSUE THREAD

**Issue by peterszerzo** [elmcph/elmcph#15]
Elm Copenhagen December 2016 Meetup

**Date**: December 1st, 2016
**Time**: 18.00 - 21.00
**Location**: Airtame, Vestergade 20C (near Rådhuspladsen)
> 
> 
> 
> 
> [Map](https://goo.gl/maps/piqWVEY2kSt): 

Next year's [Elm-Conf](https://elmeurope.org/) call-for-papers deadline is rapidly approaching, and this meetup could be a great occasion to polish proposals. Maybe we can use some time at the beginning to pitch ideas high-level, show some code - perhaps in a way that is more beginner-friendly - and then break off to work on individual proposals or other projects in traditional ElmCph style.

I could talk about multiplayer games, like [Lettero](https://lettero-27803.firebaseapp.com/).

* * *
We need to find and decide upon:

  * [ ] a venue
  * [ ] a date
  * [ ] a time
  * [ ] food/drink/snacks available: <YES/NO>

**Comment by lorenzo** [comment]
I'll create the meet up event
