### ISSUE TITLE
Logo for our Github account

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#3]
If anybody is good with designing stuff - mayby you could take a stab at a logo for our group? Something with a leaf or a tree comes to mind, but I am just not good at those things.

**Comment by cyberglot** [comment]
My initial idea was:

``` svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 323.141 322.95" enable-background="new 0 0 323.141 322.95" xml:space="preserve">
<g>
  <polygon
    fill="#C8032B"
    points="161.649,152.782 231.514,82.916 91.783,82.916"/>

  <polygon
    fill="#C8032B"
    points="8.867,0 79.241,70.375 232.213,70.375 161.838,0"/>

  <rect
    fill="#C8032B"
    x="192.99"
    y="107.392"
    transform="matrix(0.7071 0.7071 -0.7071 0.7071 186.4727 -127.2386)"
    width="107.676"
    height="108.167"/>

  <polygon
    fill="#C8032B"
    points="323.298,143.724 323.298,0 179.573,0"/>

  <polygon
    fill="#C8032B"
    points="152.781,161.649 0,8.868 0,314.432"/>

  <polygon
    fill="#C8032B"
    points="255.522,246.655 323.298,314.432 323.298,178.879"/>

  <polygon
    fill="#C8032B"
    points="161.649,170.517 8.869,323.298 314.43,323.298"/>
</g>
</svg>
```

But it's more Denmark-y than CPH-y. Let's iterate. :smile:

**Comment by cem2ran** [comment]
For the people who can't read SVG :)

![elm](https://cloud.githubusercontent.com/assets/959142/10818400/89d2ff70-7e41-11e5-88c9-b7a61937ab8f.png)

**Comment by cyberglot** [comment]
Thanks, I don't have any image editor installed here.

**Comment by madsflensted** [comment]
Hi Ju,

This is a great idea 😊

What do think about using different shades of red to symbolize that we meet
in Denmark,  but come from all over the place?

Thanks, I don't have any image editor installed here.

**Comment by madsflensted** [comment]
Or use a picture of clock on the town hall,  instead of the red? Like a
clock puzzle

Just brainstorming, have no idea how that could be done in svg.

**Comment by gausby** [comment]
And for you<sup>1</sup> who are better at reading elm than svg…

``` elm
import Svg exposing (..)
import Svg.Attributes exposing (..)
import Html exposing (Html)


main : Html
main =
  svg [ version "1.1", x "0", y "0", viewBox "0 0 323.141 322.95" ]
    [ polygon [ fill "#C8032B", points "161.649,152.782 231.514,82.916 91.783,82.916" ] []
    , polygon [ fill "#C8032B", points "8.867,0 79.241,70.375 232.213,70.375 161.838,0" ] []
    , rect
        [ fill "#C8032B", x "192.99", y "107.392", width "107.676", height "108.167"
        , transform "matrix(0.7071 0.7071 -0.7071 0.7071 186.4727 -127.2386)"
        ]
        []
    , polygon [ fill "#C8032B", points "323.298,143.724 323.298,0 179.573,0" ] []
    , polygon [ fill "#C8032B", points "152.781,161.649 0,8.868 0,314.432" ] []
    , polygon [ fill "#C8032B", points "255.522,246.655 323.298,314.432 323.298,178.879" ] []
    , polygon [ fill "#C8032B", points "161.649,170.517 8.869,323.298 314.43,323.298" ] []
    ]
```

---

<sup>1</sup> Certainly not me; I just took [this example](https://github.com/evancz/elm-svg/blob/master/examples/Logo.elm), made it compile in the elm version try uses, and changed the colors.

**Comment by madsflensted** [comment]
👍

**Comment by madsflensted** [comment]
Ok - tried to change the opacity of the elements, following a long the lines of the original elm-lang logo. I have uploaded it to our github account and placed the [code here](https://gist.github.com/madsflensted/6ffa8d5ae4acb0921778)

Don't hold back if you have improvements or better ideas.
