### ISSUE TITLE
Elm Copenhagen November 2015 Meetup

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#4]
Elm Copenhagen November 2015 Meetup

**Date and time**: [Wednesday November 25.](http://www.meetup.com/Elm-Copenhagen/events/226381801/)
**Location**:

> BestBrains
> Sankt Gertruds Stræde 5, 3.sal
> 1129 København K
> [map](https://www.google.dk/maps/place/Sankt+Gertruds+Str%C3%A6de+5,+1129+K%C3%B8benhavn+K/@55.683257,12.5718373,17z/data=!4m7!1m4!3m3!1s0x4652531ac7052ecf:0xcf513d8978fa1e4d!2sSankt+Gertruds+Str%C3%A6de+5,+1129+K%C3%B8benhavn+K!3b1!3m1!1s0x4652531ac7052ecf:0xcf513d8978fa1e4d)

Proposed schedule:
18.00 - 19.00 : Hands-on intro to Elm and Signals - no experience required (@madsflensted)
19.00 - 20.45 : We team up and work on a given problem and end by sharing and discussing our solutions (group activity)
20.45 - 21.00 : Lightening demos, if you have something to show

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [x] a problem for the collaborative session
- [ ] lightening demos

**Comment by cyberglot** [comment]
I am porting a Delaunay Triangulation to Elm, hopefully I can get it done by November 25 and maybe I can demo it :smile:

**Comment by madsflensted** [comment]
Ju, that would make a great demo! Looking forward to it

**Comment by madsflensted** [comment]
ok @lehoff, the Yatzy dice roller is actually a pretty good exercise, almost ready with that one.

**Comment by madsflensted** [comment]
Thank you all for showing up!
If you missed it - you can find the slides and exercises here: http://madsflensted.github.io/elm-cph-signals/
Thanks to @mktange for adding arrow key support to the slideshow!
