### ISSUE TITLE
Elm Copenhagen January 2016 Meetup

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#5]
Elm Copenhagen January 2016 Meetup

**Date and time**: Wednesday January 27.
**Location**: 

> Prosa
> Vester Farimagsgade 37A
> 1606 København
> Denmark
> [Map](https://maps.google.com/maps?f=q&hl=en&q=Vester+Farimagsgade+37A%2C+1606%2C+dk)

Schedule: 18.00 - 21.00

We team up and work on the [Elm Architecture](https://github.com/evancz/elm-architecture-tutorial/)

For beginners, simply work your way through the tutorial.

If you want more of a challenge, just replace the counters and animating gif's with some other UI components and interactions that you think are more interesting.

Or simply bring your own web app idea, and start building it along the lines of the Elm Architecture.

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [x] a problem for the collaborative session

**Comment by madsflensted** [comment]
@naxoc do you think it would be possible for Information to host this event?

**Comment by naxoc** [comment]
@madsflensted I'm sorry, but the canteen is booked that day already. Next meetup!

**Comment by madsflensted** [comment]
@naxoc absolutely! Thanks for checking.

**Comment by valberg** [comment]
@madsflensted I could check with PROSA?

**Comment by madsflensted** [comment]
Víðir : that would be great - can you?

**Comment by valberg** [comment]
So apparently both the big rooms are booked that day - one of them could become vacant, we'll know for sure after the holidays.

There is the option of moving to the 28th where there is plenty of room?

@madsflensted

**Comment by madsflensted** [comment]
Not so good at my end - what about 26th?

**Comment by valberg** [comment]
@madsflensted I'll check - will get an answer tomorrow :smile:

**Comment by valberg** [comment]
@madsflensted It solved itself! We've got PROSA booked for the 27th of January :smiley:

**Comment by madsflensted** [comment]
That's just great!  thanks for organizing!

**Comment by valberg** [comment]
@madsflensted My pleasure! Looking forward to it! ☺️

**Comment by madsflensted** [comment]
Yes, me too. Seems about long ways away...  😊

**Comment by jacobat** [comment]
I didn't find this on meetup.com - is it the secret meetup? ;-)

**Comment by madsflensted** [comment]
It's probably a good time to announce it there. Wanted to wait until after
New years
:-)

**Comment by madsflensted** [comment]
Was thinking that we should have the (some of the) [Elm Architecture](https://github.com/evancz/elm-architecture-tutorial/) as a subject. Maybe people could bring and work on their own web app idea based on that.  Any thoughts?

**Comment by madsflensted** [comment]
If you need to test some json decoding: 
http://simonh1000.github.io/decoder.html

**Comment by madsflensted** [comment]
Thanks @valberg and Prosa for hosting this evening of Elm hacking - as always in good company!
