### ISSUE TITLE
Elm Copenhagen March 2016 Meetup

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#6]
Elm Copenhagen March 2016 Meetup

**Date**: Tuesday March 1.
**Time**: 18.00 - 21.00
**Location**: 

> Dagbladet Information
> Store Kongensgade 40C
> 1264 København K
> Go via Skt. Annæ Passage
> Map: see attached screenshot in comments below

We team up and work on the a common problem/area
- The Elm Architecture, HTTP requests and JSON decoding.

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [x] a problem for the collaborative session

**Comment by madsflensted** [comment]
@valberg could you check for venue?

**Comment by madsflensted** [comment]
or @naxoc - maybe at Information?

**Comment by naxoc** [comment]
@madsflensted Our canteen is taken that day (again!). But we have a smaller room. How many people show up normally? I haven't been to the last two meetups.

**Comment by madsflensted** [comment]
Yesterday we were about 10 people. And in December about 15.

**Comment by naxoc** [comment]
OK, I think we can fit if we are no more than 15-18 people. Should we book the room or should we wait and see if a better option comes up?

**Comment by madsflensted** [comment]
I think that would be great, if it is OK with you.

@valberg also offered to check,  but maybe that could be for the April
event.

OK, I think we can fit if we are no more than 15-18 people. Should we book
the room or should we wait and see if a better option comes up?

**Comment by valberg** [comment]
@madsflensted We can also do it at ShopGun, I might need to coordinate with the cleaning. Otherwise Information sounds like fun - we can always use ShopGun another time! cc/ @naxoc

**Comment by valberg** [comment]
@madsflensted Hah! Race condition 😜 But yeah lets say ShopGun for the April meetup :+1:

**Comment by naxoc** [comment]
Cool! I'll book the room. I'm afraid we can't provide food. Can we just ask people to bring food or any suggestions for that?

**Comment by madsflensted** [comment]
Yes let's improvise on that. I can bring some snacks.

**Comment by naxoc** [comment]
Sweet. I booked the room. The address is:
Store Kongensgade 40C
1264 KBH K

It is in Skt. Annæ Passage - and it can be a little tricky to find.

**Comment by madsflensted** [comment]
Super.

Do you think you make a small map extract to show how to find the correct
door? Or a description.

In the Elixir group we have experienced problems with hard to find places

**Comment by naxoc** [comment]
Absolutely. Here is a map:
![Map](https://www.evernote.com/l/AAg4Y7HN2IRFcLGR6UGY-NdrD1ga6LgKcL4B/image.png)

The pink line is Skt. Annæ Passage. Go in from either Bredgade or Store Kongensgade.
I'll put up some signs by the door on the day.

**Comment by madsflensted** [comment]
@naxoc absolutely perfect - looking forward to it.

I have updated the description. 
Will announce on Meetup over the weekend.

**Comment by madsflensted** [comment]
I am currently trying to put together a small Battleships game backend, that I thought we could use for working with HTTP requests and JSON decoding in The Elm Architecture.
Let's see if I get it finished in time

**Comment by madsflensted** [comment]
Battleships server http://178.62.254.16:9999/

**Comment by lorenzo** [comment]
My fork https://github.com/lorenzo/battleships-client

**Comment by madsflensted** [comment]
@naxoc Thank you for hosting this months meetup - it was actually a great place to be!

**Comment by naxoc** [comment]
:smile:
