### ISSUE TITLE
 Elm Copenhagen April 2016 Meetup 

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#7]
Elm Copenhagen April 2016 Meetup

**Date**: April 27th
**Time**: 18.00 - 21.00
**Location**: 

> ShopGun A/S
> Arne Jacobsens Allé 16, 3. floor
> 2300 Copenhagen S
> [Map](https://www.google.dk/maps/place/Arne+Jacobsens+All%C3%A9+16,+2300+K%C3%B8benhavn+S/@55.6312108,12.5743254,17z/data=!3m1!4b1!4m2!3m1!1s0x465254bbd1758373:0x61f63b88f367d298?hl=en)

If somebody wants to present something Elm'ish that they have worked on or are interested in - we will kick off with that, taking at most 15 minutes.. Afterwards everybody can work on the area that interests them the most and team up with others top get help or just share problems and progress.

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [ ] ~~a problem for the collaborative session~~
- [ ] food/drink/snacks available: <YES/NO>

**Comment by madsflensted** [comment]
@valberg is it still an option for ShopGun to host? We are targeting a Tuesday or Wednesday later in the month, so 12./13., 19./20. or 26./27.

**Comment by madsflensted** [comment]
@cem2ran would you be interested in preparing intro and example to work on relating to the Elm React Native that you mentioned on our last meeting?

**Comment by lorenzo** [comment]
I cannot participate on the 19./20. so I prefer the other options if possible at all :)

**Comment by madsflensted** [comment]
@valberg did you get a chance to check the availability?

**Comment by cem2ran** [comment]
@madsflensted sorry for the late reply. Been on vacation. @elm-native-ui is still very experimental and has undergone some change recently. Let me just check if I can create a boilerplate project we can work on as I don't think it's even viable to setup a project in the timeframe of a meetup for some. Will get back later today.

**Comment by valberg** [comment]
@madsflensted sure, both 12th or 27th are available (I can't the other days :smile:) - sorry for the late answer

**Comment by madsflensted** [comment]
@cem2ran do you think it would be better with a presentation? it sounds like it could be interesting to see/hear about.

**Comment by madsflensted** [comment]
@valberg @cem2ran would the 27th work for both of you?

**Comment by valberg** [comment]
:ok_hand: from here! And a presentation would be awesome! :clap:

**Comment by valberg** [comment]
btw. http://tech.noredink.com/post/142283641812/designing-meetups-to-build-better-communities by Evan Czaplicki :)

**Comment by madsflensted** [comment]
Yes - thats some good input. The practical format of both Elixir and Elm Copenhagen meetups come from Evan's original switch, but this post is more detailed than earlier info.

I like the idea of having people work on different things, leaving more room for different interactions.

**Comment by madsflensted** [comment]
@cem2ran (not to stalk you on this one) - would it be better if we asked you to do a 10-15 min demo of using Elm with React Native? And then people can work on what ever they think is is interesting after that.

**Comment by valberg** [comment]
@madsflensted can you update the date and location to 27th of April and ShopGun? :smile:

**Comment by cem2ran** [comment]
I could do that, no problem! But it's unclear if I'm even in DK on the 27th, awaiting a reply from elsewhere. I am here on the 26th.

**Comment by madsflensted** [comment]
@valberg it is done. Looking forward to being back at ShopGun.
I also think it would be fun to try having the format a bit like the SF one - so let's see how that goes. I will send out invites on Meetup later.

**Comment by madsflensted** [comment]
@cem2ran I hope you can make it, since our host can't make it the 26th I suggest we stay with the 27th. If you need to travel, we will look forward to your demo at following event!

**Comment by madsflensted** [comment]
(continued from twitter)
@halfzebra we use Github to organize the upcoming meetings. This is the thread for the April one, but if it is better for you there is also the thread for the [May one](#8)

**Comment by madsflensted** [comment]
Thank you @valberg and Shopgun for hosting this event. You have a really great place for this!
Hope to see you all in May #8
