### ISSUE TITLE
Elm Copenhagen May 2016 Meetup

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#8]
Elm Copenhagen May 2016 Meetup

**Date**: Thursday May 26th
**Time**: 18.00 - 21.00
**Location**: 

> Delegate A/S
> Hummeltoftevej 49
> 2830 Virum
> [Map](https://www.google.dk/maps/place/Delegate+A%2FS/@55.78163,12.4822613,17z/data=!4m13!1m7!3m6!1s0x46524e5001497d2b:0xcfad5184e66c6d24!2sHummeltoftevej+49,+2830+Virum!3b1!8m2!3d55.78163!4d12.48445!3m4!1s0x0000000000000000:0x2255efb2825e7ff3!8m2!3d55.7811715!4d12.484885)

Location is just next to Sorgenfri S-train Station, and you can reach that by taking the A-line towards Hillerød.

If somebody wants to present something Elm'ish, maybe something that they have been working on or have been looking at - we will kick off with that, taking at most 15 minutes. Afterwards everybody can work on the area that they find most interesting and team up with others to get help or just share problems and progress.

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [x] food/drink/snacks available: Yes. Delegate will sponsor drinks and snacks. If we don't find a sponsor for food - we can all chip in and get some pizzas delivered. We will arrange that on the spot.

**Comment by madsflensted** [comment]
@gentauro let's try to find some dates where Delegate and you can attend, preferably late May.

**Comment by ghost** [comment]
Hi @madsflensted 

As I can see we can choose between the Wednesday the 25th or Thursday the 26th. Our address is:

Delegate A/S
Hummeltoftevej 49
2830 Virum

Depending on how many we are, we will use our big meeting room or the canteen.

**Comment by madsflensted** [comment]
Ok. Because of overlap with this conference http://www.atthefrontend.dk/,
it is probably better to go with 26.

**Comment by ghost** [comment]
Fine with me. Thursday 26th it is :)

**Comment by madsflensted** [comment]
@gentauro  will Delegate be able to sponser something to drink/eat/snacks? 

If not we talked about organizing some fast-food on the spot, with everybody chipping in.

**Comment by ghost** [comment]
We have bunch of beers and I guess we will also have some sodas. Snacks should also be possible and we have a "very fast" Pizza place (the only one in Virum). They are great and they can make in big numbers :)

I will speak with HR tomorrow to see what we can do.

**Comment by madsflensted** [comment]
@gentauro did you have s chat with HR?

**Comment by ghost** [comment]
Sorry, I've been to busy.

No matter what, there will be food (either paid by us or by DG) :)

**Comment by ghost** [comment]
Btw, could you update the Meetup. There are a lot from DG that after an Angular 2 course we have held at the HQ, that would like to hear more about Elm.

Do we have an official speaker?

(I'm trying to convince a fellow DIKU that uses https://github.com/mattjbray/servant-elm)

**Comment by madsflensted** [comment]
I agree, and will announce on Meetup tonight.

If your "DIKU fellow" could introduce that library/tool in the intro time slot (approx 15 min) - that would be great!

**Comment by ghost** [comment]
My DIKU fellow can't do the short intro :\

**Comment by maacl** [comment]
Is there an agenda for the meetup?

**Comment by madsflensted** [comment]
Hi Martin,

The meetup is hands on, and content driven by what the attendees want to
work on.

**Comment by maacl** [comment]
Great, thanks.

**Comment by madsflensted** [comment]
Thank you all for joining and @gentauro and Delegate for hosting! Hope to see you all next month, which is being planned on issue #9

**Comment by gausby** [comment]
…and thank you Pragma for sponsoring pizza.
