### ISSUE TITLE
Elm Copenhagen June 2016 Meetup

### ISSUE THREAD

**Issue by madsflensted** [elmcph/elmcph#9]
Elm Copenhagen June 2016 Meetup

**Date**: Tuseday June 21.
**Time**: 18.00 - 21.00
**Location**: 

> Dinero Regnskabsprogram Aps
> Nygårdsvej 5, 2. sal
> 2100 Copenhagen Ø
> [Map](https://www.google.dk/maps/place/Nyg%C3%A5rdsvej+5,+2100+K%C3%B8benhavn/@55.7123581,12.5751529,17z/data=!4m13!1m7!3m6!1s0x465252f4619bcfad:0x1375aeb90d1d15f9!2sNyg%C3%A5rdsvej+5,+2100+K%C3%B8benhavn!3b1!8m2!3d55.712346!4d12.576494!3m4!1s0x465252f4619bcfad:0x1375aeb90d1d15f9!8m2!3d55.712346!4d12.576494)

If somebody wants to present something Elm'ish, maybe something that they have been working on or have been looking at - we will kick off with that, taking at most 15 minutes. Afterwards everybody can work on the area that they find most interesting and team up with others to get help or just share problems and progress.

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] food/drink/snacks available: Dinero will sponsor some drinks and some food.

**Comment by madsflensted** [comment]
@halfzebra - just planning ahead. Would you and Dinero be willing to host a meetup in June?

**Comment by halfzebra** [comment]
@madsflensted Dinero will host the next meetup and provide some food (pizza or sandwiches)

We're considering 21th or 22th of June for the meetup.

Please elaborate.

**Comment by madsflensted** [comment]
@halfzebra that is perfect. I have updated the basics - lets give it a day to see if somebody has a preference.

**Comment by madsflensted** [comment]
@halfzebra so should we settle on of the days? I would suggest Tuesday June 21.

**Comment by halfzebra** [comment]
@madsflensted sounds good to me.

**Comment by madsflensted** [comment]
Ok - date is set and I have announced on Meetup
